# Generated by Django 4.0.5 on 2022-07-13 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='hobbies2',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='hobbies3',
        ),
        migrations.DeleteModel(
            name='Hobbies2',
        ),
        migrations.DeleteModel(
            name='Hobbies3',
        ),
    ]
