# Generated by Django 4.0.5 on 2022-07-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_remove_customuser_hobbies2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='hobbies',
            field=models.CharField(choices=[('F', 'Football'), ('D', 'Drawing'), ('d', 'Dancing'), ('B', 'Baseball'), ('R', 'Running')], default='d', max_length=1),
        ),
    ]
