# Generated by Django 4.0.5 on 2022-07-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_alter_customuser_hobbies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='hobbies',
            field=models.CharField(choices=[('F', 'Football'), ('D', 'Drawing'), ('d', 'Dancing'), ('B', 'Baseball'), ('R', 'Running')], default='d', max_length=1, null=True),
        ),
    ]
