# Generated by Django 4.0.5 on 2022-07-20 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0004_alter_customuser_hobbies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
